# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-09 14:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_kr', models.CharField(max_length=10)),
                ('name_eng', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=30)),
                ('career', models.TextField(default='현재 경력 사항이 없습니다.')),
                ('sophomore', models.TextField(default='현재 학력 사항이 없습니다.')),
                ('cert', models.TextField(default='현재 자격증 사항이 없습니다.')),
                ('skill', models.TextField(default='현재 기술 사항이 없습니다.')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
