# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-14 12:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='video_key',
            field=models.CharField(default='', max_length=30),
        ),
    ]
