# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-20 11:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_remove_video_video_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dev',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dev_title', models.CharField(default='필수 요소 입니다.', max_length=50)),
                ('dev_content', models.TextField(default='MarkDown 형식에 맞추어 작성해야 합니다.')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
