# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-20 14:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_dev_dev_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='dev',
            name='dev_git_link',
            field=models.CharField(default='No link.', max_length=50),
        ),
    ]
